name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: sudo apt install libx11-dev
      - run: zig build -Dtarget=x86_64-linux -Drelease-fast -Dcpu=x86_64
      - run: zig build -Dtarget=x86_64-windows -Drelease-fast -Dcpu=x86_64
      - run: zig build-lib -target wasm32-freestanding -dynamic -O ReleaseFast src/wasm.zig
      - uses: actions/upload-artifact@v2
        with:
          name: Game
          path: zig-out/bin/Game
      - uses: actions/upload-artifact@v2
        with:
          name: Game.exe
          path: zig-out/bin/Game.exe
