name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: apt install libx11-dev
      - run: zig build -Drelease-fast -Dcpu=x86_64
      - run: zig build  -Dtarget=x86_64-windows -Drelease-fast -Dcpu=x86_64
      - uses: actions/upload-artifact@v2
        with:
          name: binary
          path: |
            zig-out/bin/Game
            zig-out/bin/Game.exe
